__appname__ = 'HaiChatGPT'
__version__ = '0.0.7'
__version_suffix__ = 'Stable'  # version suffix, like: 1.0.0-Dev, Beta, Stable
__author__ = 'ZhengDe Zhang'
__email__ = 'zdzhang@ihep.ac.cn'
__affiliation__ = 'CC, IHEP, CAS'
__supervisor__ = 'FaZhi Qi'
__collaborator__ = ''
__url__ = 'https://github.com/zhangzhengde0225/HaiChatGPT'
